schema_version = "1.0.0"
id = "OffsetAnim"
version = "1.3.0"
name = "Offset Animation"
tagline = "Allows you to make multiple copies and offset animation"
maintainer = "Blender Bob"
type = "add-on"
website = "https://github.com/riouxr/Offset-animation"
tags = ["Camera","Tracking"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 Robert Rioux"]